rvm:
  - 2.1.1
  - 2.2.4
  - 2.3.1
  - 2.4.2

gemfile:
  - gemfiles/activerecord_4.1.14.gemfile
  - gemfiles/activerecord_4.2.8.gemfile
  - gemfiles/activerecord_5.0.3.gemfile
  - gemfiles/activerecord_5.1.4.gemfile

matrix:
  exclude:
    # rails 5 requires ruby 2.2.2+
    - gemfile: gemfiles/activerecord_5.0.3.gemfile
      rvm: 2.1.1
    - gemfile: gemfiles/activerecord_5.1.4.gemfile
      rvm: 2.1.1
    # activerecord < 4.2.8 will not run on Ruby 2.4+
    - gemfile: gemfiles/activerecord_4.1.14.gemfile
      rvm: 2.4.2

addons:
  code_climate:
    repo_token: 3717b597b3cfb358b4fa351f678e19be53e753d60f35a9172b3a5d56549c01b7
after_success:
  - bundle exec codeclimate-test-reporter
