rvm:
  - 2.2.10
  - 2.3
  - 2.4
  - 2.5
  - 2.6

gemfile:
  - gemfiles/activerecord_4.2.10.gemfile
  - gemfiles/activerecord_5.0.7.gemfile
  - gemfiles/activerecord_5.1.6.gemfile
  - gemfiles/activerecord_5.2.0.gemfile
