rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

gemfile:
  - gemfiles/activerecord_4.2.11.1.gemfile
  - gemfiles/activerecord_5.0.7.2.gemfile
  - gemfiles/activerecord_5.1.6.2.gemfile
  - gemfiles/activerecord_5.2.2.1.gemfile
  - gemfiles/activerecord_6.0.0.beta3.gemfile

# rails 6 requires ruby 2.5+
matrix:
  exclude:
    - rvm: 2.3
      gemfile: gemfiles/activerecord_6.0.0.beta3.gemfile
    - rvm: 2.4
      gemfile: gemfiles/activerecord_6.0.0.beta3.gemfile
