rvm:
  - 2.1.10
  - 2.2.8
  - 2.3.5
  - 2.4.2

gemfile:
  - gemfiles/activerecord_4.1.16.gemfile
  - gemfiles/activerecord_4.2.10.gemfile
  - gemfiles/activerecord_5.0.6.gemfile
  - gemfiles/activerecord_5.1.4.gemfile

matrix:
  exclude:
    # rails 5 requires ruby 2.2.2+
    - gemfile: gemfiles/activerecord_5.0.6.gemfile
      rvm: 2.1.10
    - gemfile: gemfiles/activerecord_5.1.4.gemfile
      rvm: 2.1.10

addons:
  code_climate:
    repo_token: 3717b597b3cfb358b4fa351f678e19be53e753d60f35a9172b3a5d56549c01b7
after_success:
  - bundle exec codeclimate-test-reporter
