rvm:
  - 2.3
  - 2.7
  - ruby-head

gemfile:
  - gemfiles/activerecord_5.1.7.gemfile
  - gemfiles/activerecord_5.2.4.1.gemfile
  - gemfiles/activerecord_6.0.2.1.gemfile

before_install:
  - gem install bundler -v 1.17.3

matrix:
  exclude:
    # rails 6 requires ruby 2.5+
    - rvm: 2.3
      gemfile: gemfiles/activerecord_6.0.2.1.gemfile
