rvm:
  - 2.3
  - 2.6
  - ruby-head

gemfile:
  - gemfiles/activerecord_4.2.11.1.gemfile
  - gemfiles/activerecord_5.0.7.2.gemfile
  - gemfiles/activerecord_5.1.6.2.gemfile
  - gemfiles/activerecord_5.2.2.1.gemfile
  - gemfiles/activerecord_6.0.0.beta3.gemfile

before_install:
  - gem install bundler -v 1.17.3

matrix:
  exclude:
    # rails 6 requires ruby 2.5+
    - rvm: 2.3
      gemfile: gemfiles/activerecord_6.0.0.beta3.gemfile
    # rails 4 requires an older bundler
    - rvm: ruby-head
      gemfile: gemfiles/activerecord_4.2.11.1.gemfile
