name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ '2.3', '2.7', '3.0', 'ruby-head' ]
        activerecord: [ '5.2.6', '6.1.4.1', '7.0.1' ]
        exclude:
          - ruby: '2.3'
            activerecord: '7.0.1' # rails 7 requires ruby >= 2.7
          - ruby: '2.3'
            activerecord: '6.1.4.1' # rails 6 requires ruby >= 2.5
          - ruby: '3.0'
            activerecord: '5.2.6' # rails < 6 crashes on ruby 3 due to kwargs changes
          - ruby: 'ruby-head'
            activerecord: '5.2.6' # rails < 6 crashes on ruby 3 due to kwargs changes

    env:
      CODECOV_TOKEN: '69b1a286-6f1c-4599-b715-74ad2db7728d'

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: BUNDLE_GEMFILE=./gemfiles/activerecord_${{matrix.activerecord}}.gemfile bundle install --jobs 4
      - name: Test with activerecord ${{matrix.activerecord}}
        run: BUNDLE_GEMFILE=./gemfiles/activerecord_${{matrix.activerecord}}.gemfile bundle exec rake
