name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ '2.3', '2.7', 'ruby-head' ]
        activerecord: [ '5.1.7', '5.2.4.4', '6.1.0' ]
        exclude:
          - ruby: '2.3'
            activerecord: '6.1.0' # rails 6 requires ruby >= 2.5
          - ruby: 'ruby-head'
            activerecord: '5.1.7' # rails < 6 crashes on ruby 3 due to kwargs changes
          - ruby: 'ruby-head'
            activerecord: '5.2.44' # rails < 6 crashes on ruby 3 due to kwargs changes

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: BUNDLE_GEMFILE=./gemfiles/activerecord_${{matrix.activerecord}}.gemfile bundle install --jobs 4
      - name: Test with activerecord ${{matrix.activerecord}}
        run: BUNDLE_GEMFILE=./gemfiles/activerecord_${{matrix.activerecord}}.gemfile bundle exec rake
